### ISSUE TITLE
systemd dynamic users

### ISSUE THREAD

**Issue by nixinator** [Platonic-Systems/secrix#14]
Secrets cannot be used in a systemd service with dynamic user = true;

**Comment by pinktrink** [comment]
Secrix will work with `DynamicUser=true`. It will not work when both `DynamicUser=` and `User=` are set, unless the user specified in `User=` exists. This will have to be looked into in the future, but for now this should be considered wontfix.

**Comment by pinktrink** [comment]
Come to think of it, the `chmod`/`chown` portion of this will not work when `DynamicUser=true`. I will look into fixing that.
