### ISSUE TITLE
`--all-systems` doesn't seem to work

### ISSUE THREAD

**Issue by chrillefkr** [Platonic-Systems/secrix#8]
Running something like `nix run .\#secrix create secrets/something -- --all-users --all-systems` gives an error message similar to `hostKeys: bad array subscript`. Seems to be a typo in `flake.nix:132`, i.e. `recips+="''${hostKeys["$1"]}"` sould be `recips+="''${hostKeys[@]}"`.

```diff
diff --git a/flake.nix b/flake.nix
index 3fe64b1..9f5aa5f 100644
--- a/flake.nix
+++ b/flake.nix
@@ -129,7 +129,7 @@
             };
             all-systems = {
               run = ''
-                recips+="''${hostKeys["$1"]}"
+                recips+="''${hostKeys[@]}"
               '';
               takes = 0;
             };
```

**Comment by pinktrink** [comment]
I will look into this, thanks!
